# Generated by Django 5.2.7 on 2025-12-04 10:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='stadion nomi')),
                ('address', models.CharField(max_length=500, verbose_name='stadion manzili')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='soatiga narxi (UZS)')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='stadion lokasiyasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stadiums', to=settings.AUTH_USER_MODEL, verbose_name='stadion egasi')),
            ],
            options={
                'verbose_name': 'stadion',
                'verbose_name_plural': 'stadionlar',
            },
        ),
    ]
