# Generated by Django 5.2.7 on 2025-12-08 08:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='stadion lokasiyasi'),
        ),
    ]
