# Generated by Django 5.2.7 on 2025-12-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_alter_stadium_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stadium_images/')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.stadium', verbose_name='stadion')),
            ],
            options={
                'verbose_name': 'rasm',
                'verbose_name_plural': 'rasmlar',
            },
        ),
    ]
