# Generated by Django 5.2.7 on 2025-12-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0003_stadiumimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='boshlanish vaqti')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="o'yin narrxi")),
                ('payment_status', models.CharField(choices=[('PAID', 'paid'), ('PENDING', 'pending'), ('CANCELED', 'canceled')], max_length=20)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_stadium', to='stadiums.stadium', verbose_name='book qilingan stadion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL, verbose_name='book qilgan user')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
